WT-3401 Lint and minor cleanup (#3491)
* Remove unnecessary line breaks.

* Fix a couple of copyrights.

* Whitespace/Indentation.

* Don't treat booleans as type "int".

* Dump out the WT_UPDATE structure timestamp information when debugging.

* Simplify a couple of expressions in the btree row-store search function.
Normally I wouldn't bother, but, well, it's the row-store search function.

* Lint hates having a variable declared in an inline include file that's
never used in the file, it complains about it for every single occurrence.

Make zero_timestamp alocal variable by creating __wt_timestamp_set_zero().

Add __wt_timestamp_set_inf() as well, that way we don't hard-code the 0xff
initialization in rec_write.c.

* Split constant string to avoid spell complaints.

* Add missing comments to new timestamp functions.

* Make the debug code build w/o timestamps.

* Minor cleanups for util_downgrade: Fix a comment (there isn't a table
name argument), remove an "else" clause after a return, remove the
verbose output of a newline, as far as I can tell, downgrade doesn't
report progress.

* bt_debug.c:1005:4: error: dereferencing type-punned pointer will break
strict-aliasing rules [-Werror=strict-aliasing]

* lint: quit futzing around with pointers, do the copy.

* Update the .gitignore list.