WT-3174 Coverity/lint cleanup (#3293)
* WT-3174 Coverity/lint cleanup

clang38 complaints:

wt3135_search_near_collator/main.c:75:22: error: implicit conversion loses
      integer precision: 'int64_t' (aka 'long') to 'int'
      [-Werror,-Wshorten-64-to-32]
                *cmp = compare_int(pkey1, pkey2);
                       ~~~~~~~~~~~ ^~~~~
wt3135_search_near_collator/main.c:75:29: error: implicit conversion loses
      integer precision: 'int64_t' (aka 'long') to 'int'
      [-Werror,-Wshorten-64-to-32]
                *cmp = compare_int(pkey1, pkey2);
                       ~~~~~~~~~~~        ^~~~~

* Coverity complains in __split_root():

dead_error_condition: The switch value complete cannot be WT_ERR_PANIC.
CID 1371132 (#1 of 1): Logically dead code (DEADCODE)
dead_error_begin: Execution cannot reach this statement: case WT_ERR_PANIC:.

Revert a minor part of 7f5d0f9, don't switch to benign error mode
(setting WT_ERR_IGNORE) until after the split has been verified in
DIAGNOSTIC mode. That makes sense and should make Coverity happy.

* Fix type-casting, sizeof()/sizeof() is a size_t.