Fix compiler warning:
../../../test/huge/huge.c:212:2: error: ignoring return value of
‘system’, declared with attribute warn_unused_result
[-Werror=unused-result]
  (void)system("rm -rf WT_TEST");