error: 'rle_start' may be used uninitialized in this function [-Werror=maybe-uninitialized]
The compiler doesn't know that if the on-page cell has a non-zero RLE,
the lookup in the page's array of repeat values will have succeeded.