SERVER-17063 fixed filemd5 compilation error: control reaches end of non-void function
(cherry picked from commit 2bde42b58c09c90aaf529f6bedea9c1bd76e91dd)