Switch the drop code back to using the WT_TABLE struct, fix a bug that was causing test_drop_create failures:
FAIL: test_drop_create (test_drop_create.test_drop_create)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/jenkins/jobs/wiredtiger-test-unit/workspace/test/suite/test_drop_create.py", line 26, in test_drop_create
    self.assertEqual(s.drop("table:test"), 0)
AssertionError: -31803 != 0